# Flags for our UI
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: strimzi-feature-gates-flags
  namespace: myproject
  labels:
    app: open-feature-demo
spec:
  flagSpec:
    flags:
      ContinueReconciliationOnManualRollingUpdateFailure:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'on'
      new-welcome-message:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'off'
      hex-color:
        variants:
          red: c05543
          green: 2f5230
          blue: 0d507b
          yellow: d4ac0d
        defaultVariant: blue
        state: ENABLED
        targeting:
          if:
            - in:
                - '@faas.com'
                - var:
                    - email
            - yellow
            - null
