apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: strimzi-feature-gates-flags
  labels:
    app: strimzi-feature-flags
spec:
  flagSpec:
    flags:
      ContinueReconciliationOnManualRollingUpdateFailure:
        variants:
          'on': true
          'off': false
        defaultVariant: 'off'
        state: ENABLED
        targeting:
          if:
            - or:
               - "==":
                  - var: clusterName
                  - "my-cluster"
               - "==":
                  - var: clusterName
                  - "my-cluster-2"
            - "on"
            - "off"
