# Triggers
# This pipeline will be triggered every Saturday at 04:00 on Saturday, but it could be also triggered by github comment
trigger:
  schedules:
    - cron: 00 4 * * FRI # At 04:00 on Saturday.
      displayName: non-regression-pipeline # friendly name given to a specific schedule
      branches:
        include: main # which branches the schedule applies to
      always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

pr:
  autoCancel: false
  branches:
    include:
      - '*'

parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string
    # If releaseVersion == latest then images will be built as part of the pipeline
    default: "latest"
  - name: kafkaVersion
    displayName: Kafka Version
    type: string
    # If kafkaVersion == latest, the latest supported version of Kafka is used
    default: "latest"

jobs:
  - template: 'templates/jobs/system-tests/non-regression_jobs.yaml'
    parameters:
      releaseVersion: '${{ parameters.releaseVersion }}'
      kafkaVersion: '${{ parameters.kafkaVersion }}'

